Funcionalidade/devolucao de livro
jordisilvazup/bibliotecaVirtual pull request #7
Opened 2021-08-31 13:28 UTC by jordisilvazup

terminando  o projeto da biblioteca virtual, 96% de cobertura em linhas e 100% e classes

2021-09-02 20:42 UTC, yurioliveirazup requested changes

2021-09-08 18:49 UTC, yurioliveirazup approved these changes

2021-09-08 18:49 UTC, yurioliveirazup commented on src/test/java/br/com/zup/edu/biblioteca/validators/DevolucaoDeEmprestimoValidatorTest.java
> +class DevolucaoDeEmprestimoValidatorTest {
Uma pergunta que eu não fiz, quanto de cobertura de testes é a sua meta e quanto que conseguiu cobrir de testes o projeto?

2021-09-08 19:49 UTC, merged

2021-09-08 19:50 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/biblioteca/controller/requests/CadastroDevolucaoLivroRequest.java
> +    public Devolucao paraDevolucao(EntityManager manager) {
ele utilizará a transação acima.

2021-09-08 19:50 UTC, jordisilvazup commented on src/test/java/br/com/zup/edu/biblioteca/validators/DevolucaoDeEmprestimoValidatorTest.java
> +class DevolucaoDeEmprestimoValidatorTest {
Não havia meta, porém foi atingido 96% de corbertura.

2021-09-08 19:50 UTC, jordisilvazup commented on src/main/java/br/com/zup/edu/biblioteca/controller/requests/CadastroDevolucaoLivroRequest.java
> +        Usuario usuario = manager.find(Usuario.class, idUsuario);
Seria lançado uma exeception pelo JPA